# Fundamentos de Matlab

## Objetivos

- Aprender como números reais e complexos são atribuídos a variáveis.
- Aprender como vetores e matrizes são atribuídos valores usando atribuição simples, o operador de cor, e as funções LINSPACE e LOGSPACE.
- Compreender as regras de precedência para a construção de expressões matemáticas.
- Ganhar uma compreensão geral de funções internas do MATLAB e como você pode aprender mais sobre elas com o Menu de Ajuda do MATLAB.
- Aprender a usar vetores para criar um gráfico de linha simples com base em uma equação.

## O ambiente de desenvolvimento MATLAB

- MATLAB possui três janelas principais:
    - Janela de Comandos - usada para inserir comandos e dados
    - Janela de Gráficos - usada para exibir desenhos e graficos
    - Janela de Edição - usada para criar e editar arquivos texto com extensão M
- Dependendo da arquitetura do seu computador e da versão do MATLAB, essas janelas podem ter aparências diferentes.

## Modo Calculadora
- A janela de comando do MATLAB pode ser usada como uma calculadora onde você pode digitar comandos linha por linha. 

- Sempre que um cálculo é realizado, MATLAB irá atribuir o resultado à variável interna $ans$

Exemplo:

In [1]:
55 - 16

ans =  39


## Variáveis do MATLAB

- A variável $ans$ pode ser útil para a realização de cálculos rápidos, mas a sua natureza transitória torna a menos útil para a programação.
- O MATLAB permite atribuir valores aos nomes de variáveis. Isto resulta no armazenamento de valores em locais de memória correspondentes ao nome da variável.
- O MATLAB pode armazenar valores individuais, bem como matrizes; ele pode armazenar dados numéricos e de texto (que na verdade é armazenado numericamente tambem).
- O MATLAB não exige que você pré-inicialize (declare) uma variável; Se ela não existir, o MATLAB irá criá-la para você.

## Constantes

- Para atribuir um único valor a uma variável, basta digitar o nome da variável, o sinal de igual (=), e o valor:

In [3]:
a = 4

a =  4


- Note que nomes de variáveis devem começar com uma letra, embora possam conter letras, números, e o símbolo de sublinhado (_)
- Você pode informar ao MATLAB para não exibir o resultado de um cálculo, acrescentando o ponto e vírgula (;) ao final de uma linha. O cálculo ainda será realizado!
- Você pode pedir ao MATLAB para exibir o valor armazenado em uma variável digitando seu nome, sem o ponto e vírgula (;):

In [5]:
a

a =  4


- Você pode usar a variável complexa i (ou j) para representar numeros imaginarios.
- Você pode pedir ao MATLAB para exibir os valores de usando vários formatos diferentes, utilizando o comando FORMAT. - Observe que os valores ainda são armazenados da mesma forma, eles são apenas exibidos na tela de forma diferente.  

Alguns exemplos:
    - short – formato de ponto fixo com 5 digitos
    - long – formato de ponto fixo com 15 digitos para DOUBLE e 7 digitos para SINGLE

Exemplos de Formatos:

In [9]:
format long; pi

ans =  3.141592653589793


In [10]:
format short; pi

ans =  3.1416


In [11]:
pi*10000

ans =  31415.92654


- Note que o formato permanece o mesmo a menos que o comando format seja executado novamente.

## Vetores e Matrizes

- O MATLAB pode tratar automaticamente arranjos de dados retangulares - matrizes unidimensionais são chamados vetores e matrizes bidimensionais são chamados de matrizes.
- Arranjos de dados, seja vetores ou matrizes, são definidos usando colchetes [ e ] no MATLAB
- Entradas dentro de uma mesma linha da matriz são separadas por espaços ou vírgulas
- Diferentes linhas da matriz são separadas por ponto e vírgula 

Exemplos de Vetores:

In [12]:
a = [1 2 3 4 5 ]

a =

   1   2   3   4   5



In [13]:
b = [2;4;6;8;10]

b =

    2
    4
    6
    8
   10



## Matrizes
- Um arranjo 2-D, ou matriz, de dados é inserido linha por linha, com espaços (ou vírgulas) separando entradas dentro da linha e o ponto e vírgula separando as linhas :

In [14]:
A = [1 2 3; 4 5 6; 7 8 9]

A =

   1   2   3
   4   5   6
   7   8   9



## Comandos úteis de arranjos de dados
- O operador de transposição (apóstrofo) pode ser usado para inverter uma matriz sobre sua própria diagonal. Por exemplo, se b é um vector-linha, b’ é um vector-coluna.
- A janela de comandos permite que você separe linhas com a tecla ENTER. O mesmo é valido em arquivos de script (arquivo texto com extensão M)
- O comando WHO o nome das variáveis usadas; Ele também fornece o tamanho, memória e tipos de dados para os arranjos de dados (matrizes e vetores).


In [15]:
b'

ans =

    2    4    6    8   10



In [16]:
who

Variables in the current scope:

A    a    ans  b



## Accessando valores dos arranjos de dados
- Valores individuais (elementos) dentro de um arranjo de dados podem ser tanto lidos e definidos usando o índice de posição na matriz ou suas coordenadas no formato linha-coluna.
- O valor do índice começa com 1 para a entrada no canto superior esquerdo de uma matriz e aumenta para baixo uma coluna

Considere a matriz C abaixo de 4 linhas e 3 colunas:

In [17]:
C = [ 2     4     9;  3     3    16;  3     0     8; 10    13    17]

C =

    2    4    9
    3    3   16
    3    0    8
   10   13   17



In [19]:
C(2)
C(4)
C(13)

ans =  3
ans =  10
error: C(13): out of bound 12


As entradas também podem ser acessadas usando a linha e a coluna:
- C(2,1) retorna 3
- C(3,2) retorna 0
- C(5,1) retorna erro!

## Criação de matrizes elementares
Existem várias funções embutidas (internas) para criar arranjos de dados:
- zeros(r,c) cria uma matriz de r linhas por c colunas preenchidas com zeros
- zeros(n) cria uma matriz de n por n preenchidas com zeros
- ones(r,c) cria uma matriz de r linhas por c colunas preenchidas com o valor um
- ones(n) cria uma matriz de n por n preenchidas com o valor um

In [21]:
ones(10)

ans =

   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1



## Criação de arranjos de dados - o operador (:)
- O operador dois-pontos (:) é útil em vários contextos. 
- Ele pode ser usado para criar um arranjo de pontos espaçados de forma linear usando a notação 

    start:diffval:limit onde,
    - start é o primeiro valor no arranjo de dados, 
    - diffval é a diferença entre valores sucessivos no arranjo de dados, e
    - limit é o limite para o último valor (embora não necessariamente, o último valor).

In [22]:
1:0.6:3

ans =

    1.0000    1.6000    2.2000    2.8000



## Operador dois-pontos: observações
- Se diffval for omitido, o valor padrão é 1:

In [23]:
3:6

ans =

   3   4   5   6



- Para criar uma série decrescente, diffval deve ser negativo:

In [24]:
5:-1.2:2

ans =

    5.0000    3.8000    2.6000



- Se start+diffval>limit para uma série crescente ou start+diffval<limit  para uma série decrescente, será criado um arranjo vazio:

In [25]:
5:2

ans = [](1x0)


- Para criar uma coluna, transponha a saída do operador dois-pontos, e não do valor limite; Ou seja, faça isso (3:6)’ e não isso 3:6’

In [27]:
(3:6)'

ans =

   3
   4
   5
   6



## Criação de arranjos de dados - linspace
- Para criar um vetor-linha com um número específico de pontos espaçados de forma linear entre dois números, use o comando linspace.
- linspace(x1, x2, n) cria um arranjo linearmente espaçado de n pontos entre x1 e x2

In [29]:
linspace(0, 1, 6)

ans =

   0.00000   0.20000   0.40000   0.60000   0.80000   1.00000



- Se n for omitido, serão criados 100 pontos.
- Para gerar uma coluna, transponha a saída do comando linspace.

## Criação de arranjos de dados - logspace
- Para criar um vetor-linha com um número específico de pontos espaçado logaritmicamente entre dois números, use o comando logspace.
- logspace(x1, x2, n) cria uma matriz logaritmicamente espaçada de n pontos entre $10^{x1}$ e $10^{x2}$

In [30]:
logspace(-1, 2, 4)

ans =

     0.10000     1.00000    10.00000   100.00000



- Se n for omitido, serão criados 100.
- Para gerar uma coluna, transponha a saída do comando logspace.